### ISSUE TITLE
Query Taxpayer HU+ Wizard | Exception

### ISSUE THREAD

**Issue by Eilerant** [hungarodo/odoohu-plus#20]
In the wizard, searching for the tax number 30314052-2-51 will return an Odoo exception.

![image](https://github.com/user-attachments/assets/c4123fc2-4944-48ae-ae85-d6aa60905c61)

Error message:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/http.py", line 1782, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/http.py", line 1809, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/http.py", line 2013, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/addons/base/models/ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/src/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/extra-addons/odoohu-demo.git-66cb0637cdaa0/l10n_hu_nav_invoice/wizard/wizard.py", line 371, in action_execute
    manage_result = self.manage_nav_taxpayer()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/extra-addons/odoohu-demo.git-66cb0637cdaa0/l10n_hu_nav_invoice/wizard/wizard.py", line 662, in manage_nav_taxpayer
    manage_result = self.env['l10n.hu.nav.taxpayer'].manage_taxpayer(manage_values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/extra-addons/odoohu-demo.git-66cb0637cdaa0/l10n_hu_nav_invoice/models/nav_taxpayer.py", line 539, in manage_taxpayer
    query_result = self.do_query_taxpayer(query_values)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/odoo/odoohu17e.hungarodo.hu/extra-addons/odoohu-demo.git-66cb0637cdaa0/l10n_hu_nav_invoice/models/nav_taxpayer.py", line 730, in do_query_taxpayer
    connection._parse_error_response(response_xml)
  File "/var/odoo/odoohu17e.hungarodo.hu/src/addons/l10n_hu_edi/models/l10n_hu_edi_connection.py", line 433, in _parse_error_response
    raise L10nHuEdiConnectionError(errors)
odoo.addons.l10n_hu_edi.models.l10n_hu_edi_connection.L10nHuEdiConnectionError: INVALID_REQUEST: Helytelen kérés!
None: None
None: None

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://odoohu17e.hungarodo.hu/web/assets/edcab45/web.assets_web.min.js:2893:319
    makeErrorFromResponse@https://odoohu17e.hungarodo.hu/web/assets/edcab45/web.assets_web.min.js:2896:163
    jsonrpc/promise</<@https://odoohu17e.hungarodo.hu/web/assets/edcab45/web.assets_web.min.js:2900:34

**Comment by gezzzan** [comment]
@Eilerant fixed error message
this is HU+ pro feature, maybe move issue there
